#开关Debug模式 (开发者所用)
Debug: false
#体力恢复时间 (单位:tick)  20tick = 1s
RecoveryTime: 20
#体力
Stamina:
  #体力组 (默认组 请勿删除)
  Default:
    # 玩家最大体力
    Value: 100
    # 玩家体力恢复速度
    Recovery:
      Min: 5
      Max: 10
  VIP:
    # 玩家最大体力
    Value: 300
    # 玩家体力恢复速度
    Recovery:
      Min: 10
      Max: 20
  MVP:
    # 玩家最大体力
    Value: 500
    # 玩家体力恢复速度
    Recovery:
      Min: 10
      Max: 30
#事件 (需要重启服务器生效)
Listener:
  # 玩家奔跑时
  Sprint:
    #开关
    Enable: true
    # 消耗体力
    Value: 1
  # 玩家移动时
  Move:
      #开关
    Enable: false
      # 消耗体力
    Value: 1
  # 玩家跳跃时
  Jump:
      #开关
    Enable: true
      # 消耗体力
    Value: 1
  # 玩家游泳时
  Swim:
      #开关
    Enable: true
      # 消耗体力
    Value: 1
